import type { Metadata } from "next";
import "./globals.css";
import ClientProviders from "@/components/client-providers";
import Subscribe from "@/components/Subscribe";
import Footer from "@/components/Footer";
import About from "@/components/About";
import { Almarai } from "next/font/google";
import { cn } from "@/lib/utils";

const sansFont = Almarai({
  weight: ["400", "700"],
  subsets: ["arabic"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(sansFont.variable, "font-sans antialiased")}
        dir="rtl"
      >
        <main>
          <ClientProviders>{children}</ClientProviders>
        </main>
        <Subscribe />
        <About />
        <Footer />
      </body>
    </html>
  );
}
